config/routes.rb
Rails.application.routes.draw do
  resources :businesses, only: [ :index, :new, :create, :edit, :update, :show ] do
    resources :business_comments, only: [ :create, :index, :destroy ]
    resources :business_addresses do
      resources :events do
        resources :event_participations, only: [ :create ]
      end
      resource :cardapio, only: [ :new, :create, :edit, :update, :show ] do
        resources :item_cardapio_comments, only: [ :create, :index, :destroy ]
      end
    end

    # Rotas para seguir/deixar de seguir bares
    member do
      post :follow, to: "business_relationships#create"
      delete :unfollow, to: "business_relationships#destroy"
    end
  end

  resources :profiles
  resources :posts, only: [ :show, :new, :edit, :create, :update, :destroy ] do
    scope module: :posts do
      resources :reactions, only: [ :create, :destroy ]
      resources :comments, only: [ :new, :create, :index, :destroy ]
    end
  end

  resources :events, only: [ :new, :create, :show ] do
    resource :my_availability, only: [ :show, :create, :update ], controller: "event_availabilities"
  end

  resources :items_consumed do
    collection do
      get :summary
    end
  end
  post :add_item_consumed, to: "items_consumed#create", as: "add_item_consumed"
  get :consumption_ranking, to: "items_consumed#ranking", as: "consumption_ranking"
  post :celebrate_user, to: "users#celebrate_user", as: "celebrate_user"
  get :friends_ranking, to: "items_consumed#friends_ranking", as: "friends_ranking"

  # Rota para remover imagem de um post
  delete "remove_image/:signed_id", to: "posts#remove_image", as: :remove_image

  resources :groups
  resources :friendships
  resources :relationships, only: [ :create, :destroy ]
  resources :business_relationships, only: [ :create, :destroy ]

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }


  # Rotas para followers/following de usuários
  resources :users, only: [] do
    member do
      get :followers
      get :following
      post :follow, to: "relationships#create"
      delete :unfollow, to: "relationships#destroy"
      get :groups
      get :following_businesses
    end
  end

  post :add_member, to: "groups#add_member"
  post :remove_member, to: "groups#remove_member"
  post :add_rating, to: "businesses#add_rating"
  post :add_item_rating, to: "item_cardapios#add_rating"
  get "pages/userindex", as: "userindex"
  get "pages/barindex", as: "barindex"

  get "feed", to: "feed#show", as: :feed

  get "up" => "rails/health#show", as: :rails_health_check

  get "feed/search", to: "feed#search", as: "search_users"
  get "feed/search_shops", to: "feed#search_shops", as: "search_shops"
  get "feed/search_bars", to: "feed#search_bars", as: "search_bars"

  authenticated :user do
    root to: "feed#show", as: :authenticated_user_root
  end

  root "pages#home"
end

app/controllers/items_consumed_controller.rb
class ItemsConsumedController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item, only: %i[ show edit update destroy check_user ]
  before_action :set_user, only: %i[ index ]
  before_action :check_user, only: %i[ destroy ]

  def summary
    @summary = ItemConsumed
                .select("name, brand, item_type, SUM(quantity) AS total_quantity")
                .group(:name, :brand, :item_type)
                .order("total_quantity DESC")
  end

  def ranking
    @rankings = User
                .joins(:items_consumed)
                .select("user_id, username, SUM(worth * quantity) AS points")
                .group(:username)
                .order("points DESC")
  end

  def friends_ranking
    connections = User.where(id: current_user.following_ids).or(User.where(id: current_user.follower_ids))
    @friends = User
                  .joins(:items_consumed)
                  .select("user_id, username, SUM(worth*quantity) AS points, date")
                  .group(:username)
                  .order("points DESC")
    @start = params[:start_date]
    @end = params[:end_date]
    if @start != "" && @end != ""
      @friends = @friends.where("date BETWEEN ? AND ?", @start, @end)
    end
  end

  def show
  end

  def new
    @item = current_user.items_consumed.build
    @items = ItemCardapio.order(cardapio_id: :desc)
  end

  def index
    @items = ItemConsumed.where(user: @user).order(date: :desc)
  end

  def update
    if @item.update(items_consumed_params)
      redirect_to profile_path(@user.profile), notice: "Report was successfully updated!"
    else
      render :edit
    end
  end

  def edit
  end

  def create
    @item = current_user.items_consumed.new(items_consumed_params)
    @user = current_user
    @brand = items_consumed_params[:brand]
    @name = items_consumed_params[:name]
    @type = items_consumed_params[:item_type]

    # worth = existing_item.worth. if doesnt exist, = 0
    @business = Business.find_by(id: BusinessAddress.where(id: Cardapio.where(id: ItemCardapio.where(nome: @name).pluck(:cardapio_id)).pluck(:business_address_id)).pluck(:business_id))
    if @business&.company_name == @brand
      @worth = ItemCardapio.find_by(cardapio: Cardapio.find_by(business_address_id: @business.business_addresses)).worth
    else
      @worth = 0
    end
    if ItemConsumed.where(user: @user, brand: @brand, item_type: @type, name: @name).exists?
      @old_item = ItemConsumed.find_by(user: @user, brand: @brand, item_type: @type, name: @name)
      new_quantity = @old_item.quantity + @item.quantity
      @old_item.update(quantity: new_quantity, worth: @worth)
      if @old_item.save
        redirect_to items_consumed_index_path(user_id: @user.id), notice: "item updated!"
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    else
      if @item.save
        redirect_to items_consumed_index_path(user_id: @user.id), notice: "new item created!"
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @item.update(items_consumed_params)
        format.html { redirect_to @item, notice: "Item was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @item = ItemConsumed.find(params[:id])
    if @item.user == current_user
      @item.destroy
    else
      redirect_to root_path, alert: "Sem permissão para remover comentário."
    end
  end

  def check_user
    return if @item.user == current_user

    redirect_to root_path, notice: "You're not the owner."
  end

  private

  def set_item
    @item = ItemConsumed.find(params[:id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def items_consumed_params
    params.require(:item_consumed).permit(:item_consumed_id, :name, :quantity, :brand, :item_type, :date, :worth)
  end
end

app/views/items_consumed/_form.html.erb
<%= form_with(model: item_consumed, url: add_item_consumed_path, local: true, class: "space-y-8") do |form| %>
    <% if item_consumed.errors.any? %>
        <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded">
        <h2 class="font-semibold mb-2"><%= pluralize(item_consumed.errors.count, "error") %> proibiu este item de ser salvo:</h2>
        <ul class="list-disc list-inside space-y-1">
            <% item_consumed.errors.each do |error| %>
            <li><%= error.full_message %></li>
            <% end %>
        </ul>
        </div>
    <% end %>

    <div>
        <%= form.label "Nome", class: "block text-gray-700 font-medium mb-1" %>
        <%= form.text_field :name, class: "w-full border border-gray-300 rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500" %>
    </div>

    <div>
        <%= form.label "Tipo", class: "block text-gray-700 font-medium mb-1" %>
        <%= form.select :item_type, options_for_select(ItemConsumed.item_types.keys.map { |k| [k.humanize] }) , class: "w-full border border-gray-300 rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500" %>
    </div>

    <div>
        <%= form.label "Quantidade", class: "block text-gray-700 font-medium mb-1" %>
        <%= form.number_field :quantity, direct_upload: true, class: "w-full border border-gray-300 rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500" %>
    </div>

    <div>
        <%= form.label "Marca", class: "block text-gray-700 font-medium mb-1" %>
        <%= form.text_field :brand, class: "w-full border border-gray-300 rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500" %>
    </div>

    <div>
        <%= form.label "Data de Consumo", class: "block text-gray-700 font-medium mb-1" %>
        <%= form.date_field :date, class: "w-full border border-gray-300 rounded px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500" %>
    </div>

    <div>
        <%= form.submit "Confirmar", class: "bg-blue-500 hover:bg-blue-600 text-white font-semibold px-6 py-2 rounded shadow transition duration-200" %>
    </div>
<% end %>

app/views/items_consumed/_item.html.erb
<div class="border rounded-lg mt-2">
    <p class="font-bold"> <%= item.name %></p>
    <p> <%= item.quantity %> comprados</p>
    <p class="text-gray-600"> <%= item.item_type.titleize %></p>
    <p class="text-gray-600"> Feito por <%= item.brand %> </p>
    <p class="text-gray-600"> Última vez comprado: <%= time_tag item.date, class: "text-gray-500" %> </p>

    <% if current_user == item.user %>
        <%= button_to "EXCLUIR ITEM", item, method: :delete, id: "remove_item", class: "bg-red-500 px-4 py-1 text-white underline underline-offset-3", data: { confirm: "Are you sure?" } %>
    <% end %>
</div>

app/views/items_consumed/_prices.html.erb
<div>
    <h2 class="font-bold text-xl text-center"> Itens em Cardápios </h2>
    <table class="w-full spacing-x-3">
        <thead>
            <tr class="text-center">
                <th> Marca </th>
                <th> Nome </th>
                <th> Tipo </th>
                <th> Valor em Pontos </th>
            </tr>
        </thead>
        <tbody>
        <% @items.each do |item| %>
            <tr class="text-center border border-2 p-3">
                <td class="border"><%= item.cardapio.business_address.business&.company_name %> </td>
                <td class="border"><%= item.nome %> </td>
                <% if item.tipo == 0 %>
                    <td class="border">Other</td>
                <% else%>
                    <td class="border">Beer</td>
                <% end%>
                <td class="border"><%= item.worth %> </td>
            <tr>
        <% end %>
        </tbody>
    </table>
</div>

app/views/items_consumed/friends_ranking.html.erb
<div class="text-center">
    <h1 class="font-bold text-2xl"> Ranking dos amigos de < @<%= current_user.username %> ></h1>
    <div class="m-5">
    <% if @start != "" && @end != "" %>
        <h2 class="text-xl"> Filtrando pelo período de <strong><%= @start&.to_date&.strftime("%d/%m/%Y")%></strong> a <strong><%= @end&.to_date&.strftime("%d/%m/%Y")%></strong> </h2>
    <% else %>
        <h2 class="text-xl"> Sem filtros de data </h2>
    <% end %>
    </div>
    <div class=""> 
        <p> Ver ranking de <strong><%=link_to "Today", friends_ranking_path(start_date: Date.today, end_date: Date.today) %></strong></p>
    </div>

    <div>
        <%= form_with url: friends_ranking_path, method: :get, local: true do |f| %>
            <p> Filtrar por data </p>
            <div class="flex items-center mt-4 space-x-2 max-w-5xl mx-auto px-4">
                <%= f.date_field :start_date,
                    label: "Data início",
                    placeholder: Date.today,
                    class: "flex-1 border rounded p-2 focus:outline-none focus:ring-2 focus:ring-blue-400" %>
                <%= f.date_field :end_date,
                label: "Data término",
                placeholder: Date.today,
                class: "flex-1 border rounded p-2 focus:outline-none focus:ring-2 focus:ring-blue-400" %>
                <%= f.submit "Filtrar",
                    class: "px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600" %>
            </div>
        <% end %>
    </div>

    <div class="border border-2 flex flex-col items-center justify-center mt-4 p-4"">
        <% @friends.each_with_index do |user, index| %> 
            <div class="flex flex-row justify-center items-center text-center w-full">
            <p class="border py-1 w-32"> <%= index+1 %> -- <%= user.username %> </p>
            <p class="border py-1 w-32"> <%= user.points %> pontos</p> 
            </div>
        <%end%>
    </div>
</div>

app/views/items_consumed/index.html.erb
<div class="flex-column space-y-4">
    <h1 class="text-xl font-bold"> Histórico de items do <%= @user.username %> </h1>

    <div class="mt-4">
        <p>
        <% if @user == current_user %>
            <%= link_to "Adicionar novo item", new_items_consumed_path, class: "bg-green-500 hover:bg-green-600 text-white font-semibold px-3 py-3 rounded-lg shadow transition duration-200"%>
        <% end %>
        </p>
    </div>

    <div>
        <p><%= link_to "Ranking de Usuários", consumption_ranking_path, class: "bg-blue-500 hover:bg-blue-600 text-white font-semibold px-4 py-2 rounded shadow transition duration-200" %> </p>
    </div>
    
    <div class="mt-4">
        <% if @items.any? %>
            <h3 id="item_consumed">
                <%= render partial: "item", collection: @items, as: :item %>
            </h3>
        <% else %>
            <p class="text-gray-500 italic">Nenhum item ainda.</p>
        <% end %>
    </div>
</div>

app/views/items_consumed/new.html.erb
<% content_for :title, "Novo item" %>

<div class="min-h-screen flex flex-col items-center bg-gray-50 py-12">
  <h1 class="text-3xl font-bold text-blue-600 mb-8">Novo item</h1>

  <div class="flex flex-row gap-8">
    <div class="bg-white shadow-md rounded-lg p-8 w-full max-w-lg mb-6">
      <%= render "form", item_consumed: @item %>
    </div>
    <div class="bg-white shadow-md rounded-lg p-8 w-full max-w-lg mb-6">
      <%= render "prices" %>
    </div>
  </div>

  <div>
    <%= link_to "Back to feed", feed_path, class: "text-gray-600 hover:text-gray-800 font-semibold" %>
  </div>
</div>

app/views/items_consumed/ranking.html.erb
<div class="max-w-4xl text-center flex flex-col justify-items-center">
    <h1 class="font-bold text-xl"> Ranking de Consumo </h1>
    <table class="w-full spacing-x-3">
        <thead>
            <tr class="text-center">
                <th> Username </th>
                <th> Pontuação </th>
            </tr>
        </thead>
        <tbody>
        <% @rankings.each do |user| %>
            <tr class="text-center border border-2 p-3">
                <td class="border"><%= user.username %> </td>
                <td class="border"><%= user.points %> </td>
                <td class="border inline-block text-purple-700 font-semibold border-b-2 border-transparent hover:border-purple-600 transition-colors"><%= button_to "Parabenizar usuário", celebrate_user_path(user: user.user_id, points: user.points)%>
            <tr>
        <% end %>
        </tbody>
    </table>

app/views/items_consumed/show.html.erb
<%= render @item %>

app/views/items_consumed/summary.html.erb
<h1 class="text-2xl font-bold mb-6">Resumo geral de itens consumidos</h1>

<table class="min-w-full border">
  <thead>
    <tr>
      <th class="border px-2 py-1">Nome</th>
      <th class="border px-2 py-1">Marca</th>
      <th class="border px-2 py-1">Tipo</th>
      <th class="border px-2 py-1">Quantidade Total</th>
    </tr>
  </thead>

  <tbody>
    <% @summary.each do |item| %>
      <tr>
        <td class="border px-2 py-1"><%= item.name %></td>
        <td class="border px-2 py-1"><%= item.brand %></td>
        <td class="border px-2 py-1"><%= item.item_type %></td>
        <td class="border px-2 py-1 font-semibold"><%= item.total_quantity %></td>
      </tr>
    <% end %>
  </tbody>
</table>